/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import client.File;
import client.ServerAdapter;
import client.User;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mp755
 */
public class RollbackGUI extends javax.swing.JFrame {
    private ServerAdapter serverAdapt;
    private DownloadGUI downloadGUI;
    private String[] fileNames;
    private File file;
    private User user;
    /**
     * Creates new form RollbackGUI
     */
    public RollbackGUI() {
        serverAdapt = ServerAdapter.getInstance();
        initComponents();
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    
    public void setFile(File file) {
        this.file = file;
    }
    
    public void setDownloadGUI(DownloadGUI downloadGUI) {
        this.downloadGUI = downloadGUI;
    }
    
    public void updateModel() {
        fileNames = new String[3];
        
        fileNames[0] = "Original Version";
        
        if(file.getUpdateNum() > 3) {
            fileNames[1] = "Revision " + (file.getUpdateNum() - 3);
            fileNames[2] = "Revision " + (file.getUpdateNum() - 2);
        } else if (file.getUpdateNum() == 3){
            fileNames[1] = "Revision " + (file.getUpdateNum() - 2);
        } else if (file.getUpdateNum() == 1) {
            fileNames[0] = "There are no rollbacks for this file. Your version is the original.";
            fileModel.setEnabled(false);
        }
        
        fileModel.setModel(new javax.swing.AbstractListModel() {
            String[] strings = fileNames;
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(fileModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileModel = new javax.swing.JList();
        rollBackButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        downloadRollbackBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Rollback Files to Previous Versions");

        fileModel.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(fileModel);

        rollBackButton.setText("Roll Back");
        rollBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rollBackButtonMouseClicked(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        downloadRollbackBox.setText("Download Rollbacked File");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(downloadRollbackBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(rollBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rollBackButton)
                    .addComponent(cancelButton)
                    .addComponent(downloadRollbackBox))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void rollBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rollBackButtonMouseClicked
        int buttonPicked = JOptionPane.showConfirmDialog(this, "Are you sure? You will lose any changes made after the selected rollback.\nYou will not be able to undo this action.", "Are you sure?", JOptionPane.YES_NO_OPTION);
        
        if(buttonPicked == 0) {
            List<String> fileVersionList = fileModel.getSelectedValuesList();
            String fileVersion = fileVersionList.get(0);
            int revisionNum;
        
            if(fileVersion.equals("Original Version")) {
                revisionNum = 0;
            } else {
                revisionNum = fileVersion.charAt(fileVersion.length() - 1) - 48;
            }
        
            if(downloadRollbackBox.isSelected()) {
                String originalFilePath = file.getFilePath();
                file.setFilePath("temp//" + file.getFilePath());
        
                downloadGUI.downloadFile(file, revisionNum);
        
                file.setFilePath(originalFilePath);
            }
            
            if(serverAdapt.rollbackFile(file, revisionNum, "temp//" + file.getFilePath() + "//" + file.getFileName() + "_" + revisionNum, file.getFilePath() + "\\" + file.getFileName())) {
                JOptionPane.showMessageDialog(this, "File has been rolled back to selected version.");
            } else {
                JOptionPane.showMessageDialog(this, "File could not be rolled back. Please try again later.");
            }
        }
    }//GEN-LAST:event_rollBackButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RollbackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RollbackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RollbackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RollbackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RollbackGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox downloadRollbackBox;
    private javax.swing.JList fileModel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rollBackButton;
    // End of variables declaration//GEN-END:variables
}
