/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import client.Permission;
import client.ServerAdapter;
import client.User;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mp755
 */
public class ViewPermissionGUI extends javax.swing.JFrame {
    private User user;
    private int fileID;
    private List<Permission> permissionList;
    private String[] friendsNames;
    private ServerAdapter serverAdapt;
    private client.File file;

    /**
     * Creates new form ViewPermissionGUI
     */
    public ViewPermissionGUI() {
        serverAdapt = ServerAdapter.getInstance();
        initComponents();
    }
    
    public void getPermissions() {
        refreshPermissions();
        refreshPermissionsList();
        
        if(!(file.getOwner().equals(user.getUserName()))) {
            addPermButton.setEnabled(false);
            removePermButton.setEnabled(false);
        }
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    
    public void setFileID(int fileID) {
        this.fileID = fileID;
    }
    
    public void setFile(client.File file) {
        this.file = file;
    }
    
    public void refreshPermissions() {
        permissionList = serverAdapt.getPermissionsList(fileID);
        friendsNames = new String[permissionList.size()];
        
        for(int i = 0; i < permissionList.size(); i++) {
            friendsNames[i] = permissionList.get(i).getUserName();
        }
    }
    
    public void refreshPermissionsList() {
        friendsModel.setModel(new javax.swing.AbstractListModel() {
            String[] strings = friendsNames;
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(friendsModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        friendsModel = new javax.swing.JList();
        addPermButton = new javax.swing.JButton();
        removePermButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        friendsModel.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(friendsModel);

        addPermButton.setText("Add Permission");
        addPermButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPermButtonMouseClicked(evt);
            }
        });
        addPermButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPermButtonActionPerformed(evt);
            }
        });

        removePermButton.setText("Remove Permission");
        removePermButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removePermButtonMouseClicked(evt);
            }
        });

        goBackButton.setText("Go Back");
        goBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addPermButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removePermButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(goBackButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPermButton)
                    .addComponent(removePermButton)
                    .addComponent(goBackButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPermButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPermButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPermButtonActionPerformed

    private void addPermButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPermButtonMouseClicked
        AddPermissionGUI addPermGUI = new AddPermissionGUI();
        addPermGUI.addUser(user);
        addPermGUI.addFileID(fileID);
        addPermGUI.setVisible(true);
    }//GEN-LAST:event_addPermButtonMouseClicked

    private void removePermButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removePermButtonMouseClicked
        List<String> friendNames = friendsModel.getSelectedValuesList();
        Permission permission = new Permission(friendNames.get(0), fileID, 1);
        if(serverAdapt.removePermission(permission)) {
            JOptionPane.showMessageDialog(this, "Permission successfully deleted.");
        } else {
            JOptionPane.showMessageDialog(this, "Permission was not deleted. Please try again.");
        }
        
        getPermissions();
    }//GEN-LAST:event_removePermButtonMouseClicked

    private void goBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_goBackButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPermissionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPermissionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPermissionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPermissionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPermissionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPermButton;
    private javax.swing.JList friendsModel;
    private javax.swing.JButton goBackButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removePermButton;
    // End of variables declaration//GEN-END:variables
}
